name = "toot-worker"
main = "main.js"
compatibility_date = "2025-05-14"

kv_namespaces = [
  { binding = "TOOTWORKER_KV", id = "add your id here" }
]

[observability.logs]
enabled = true

invocation_logs = false